const { contextBridge, ipcRenderer, webUtils } = require("electron");
contextBridge.exposeInMainWorld("libraryAPI", {
  listLibrary: () => ipcRenderer.invoke("library:list"), listLibraryPage: (offset = 0, limit = 60) => ipcRenderer.invoke("library:list-page", { Offset: offset, Limit: limit }), searchLibraryPage: (query, offset = 0, limit = 60) => ipcRenderer.invoke("library:search-page", { Query: query, Offset: offset, Limit: limit }), titleSuggestions: () => ipcRenderer.invoke("library:title-suggestions"), ensureThumbnail: filePath => ipcRenderer.invoke("library:ensure-thumbnail", filePath), listTrash: () => ipcRenderer.invoke("library:list-trash"), listSources: () => ipcRenderer.invoke("library:list-sources"), listExclusions: () => ipcRenderer.invoke("library:list-exclusions"),
  sourceStats: () => ipcRenderer.invoke("library:source-stats"), scanLog: () => ipcRenderer.invoke("library:scan-log"), onScanProgress: callback => { const handler = (_event, update) => callback(update); ipcRenderer.on("library:scan-progress", handler); return () => ipcRenderer.removeListener("library:scan-progress", handler); }, search: query => ipcRenderer.invoke("library:search", query), updateMetadata: update => ipcRenderer.invoke("library:update-meta", update), updateAuthor: update => ipcRenderer.invoke("library:update-author", update), updateCover: update => ipcRenderer.invoke("library:update-cover", update),
  collections: () => ipcRenderer.invoke("library:collections"), createCollection: name => ipcRenderer.invoke("library:create-collection", name), addToCollection: (name, path) => ipcRenderer.invoke("library:add-to-collection", name, path), removeFromCollection: (name, path) => ipcRenderer.invoke("library:remove-from-collection", name, path), documentCollections: path => ipcRenderer.invoke("library:document-collections", path), renameCollection: change => ipcRenderer.invoke("library:rename-collection", change), deleteCollection: name => ipcRenderer.invoke("library:delete-collection", name), reorderCollections: names => ipcRenderer.invoke("library:reorder-collections", names), collectionDocuments: name => ipcRenderer.invoke("library:collection-documents", name), collectionDocumentsPage: (name, offset = 0, limit = 60, query = "") => ipcRenderer.invoke("library:collection-page", { Name: name, Offset: offset, Limit: limit, Query: query }), pickCollectionImage: () => ipcRenderer.invoke("library:pick-collection-image"), pickCoverImage: () => ipcRenderer.invoke("library:pick-cover-image"), searchCover: query => ipcRenderer.invoke("library:search-cover", query), updateCollection: appearance => ipcRenderer.invoke("library:update-collection", appearance),
  documentTags: path => ipcRenderer.invoke("library:document-tags", path), setDocumentTags: update => ipcRenderer.invoke("library:set-document-tags", update),
  addFiles: () => ipcRenderer.invoke("library:add-files"), addDroppedFiles: files => ipcRenderer.invoke("library:add-dropped-paths", Array.from(files || []).map(file => webUtils.getPathForFile(file)).filter(Boolean)), addFolder: () => ipcRenderer.invoke("library:add-folder"), excludeFolder: () => ipcRenderer.invoke("library:exclude-folder"), removeExclusion: path => ipcRenderer.invoke("library:remove-exclusion", path), setSourceScanMode: update => ipcRenderer.invoke("library:set-source-scan-mode", update), removeSource: path => ipcRenderer.invoke("library:remove-source", path), removeRecord: path => ipcRenderer.invoke("library:remove-record", path), rescan: () => ipcRenderer.invoke("library:rescan"), removeMissing: () => ipcRenderer.invoke("library:remove-missing"),
  trash: filePath => ipcRenderer.invoke("library:trash", filePath), restore: filePath => ipcRenderer.invoke("library:restore", filePath), emptyTrash: () => ipcRenderer.invoke("library:empty-trash"), cacheInfo: () => ipcRenderer.invoke("library:cache-info"), diagnostics: () => ipcRenderer.invoke("library:diagnostics"), cleanThumbnailCache: () => ipcRenderer.invoke("library:clean-thumbnail-cache"),
  openFile: filePath => ipcRenderer.invoke("library:open-file", filePath), openFolder: folderPath => ipcRenderer.invoke("library:open-folder", folderPath),
  setFullscreen: enabled => ipcRenderer.invoke("window:fullscreen", enabled), setScreenOn: enabled => ipcRenderer.invoke("window:screen-on", enabled), minimizeWindow: () => ipcRenderer.invoke("window:minimize"), toggleMaximizeWindow: () => ipcRenderer.invoke("window:toggle-maximize"), closeWindow: () => ipcRenderer.invoke("window:close"), isWindowMaximized: () => ipcRenderer.invoke("window:is-maximized"), onWindowState: callback => { const handler = (_event, state) => callback(state); ipcRenderer.on("window:state", handler); return () => ipcRenderer.removeListener("window:state", handler); }, openDefaultApps: () => ipcRenderer.invoke("system:open-default-apps"), backup: state => ipcRenderer.invoke("library:backup", state), restoreBackup: () => ipcRenderer.invoke("library:restore-backup")
});
